
/*
 * Copyright (c) Interactive Information R & D (I2RD) LLC.
 * All Rights Reserved.
 *
 * This software is confidential and proprietary information of
 * I2RD LLC ("Confidential Information"). You shall not disclose
 * such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered
 * into with I2RD.
 */

package net.venturetech.sshd_test.config;

import javax.annotation.Generated;

/**
 * Project Information.
 * @author Auto Generated (noreply@i2rd.com)
 */
@Generated(value= "Generated by build system", date = "20170116T104925.149-0600")
public final class ProjectInformation
{
    /** Application Name. */
    public static final String APPLICATION_NAME = "Starter App";
    /** Name. */
    private static final String _name = "sshd-test";
    /** Group. */
    private static final String _group = "net.venturetech";
    /** Version. */
    private static final String _version = "1.2";
    /** Commit. */
    private static final String _commit = "940d17cd393a085f28da842d2ad3fa312077ad25";
    /** Branch. */
    private static final String _branch = "master";
    /** Status: release, milestone, integration. */
    private static final String _status = "integration";

    /**
    * Utility class constructor.
    */
    private ProjectInformation()
    {
    }

    /**
     * Get the project name: "{@value #_name}"
     * @return the name.
     */
    public static String getName() 
    { 
        return _name; 
    }

    /**
     * Get the project group: "{@value #_group}"
     * @return the group.
     */
    public static String getGroup() 
    { 
        return _group; 
    }

    /**
     * Get the project version: "{@value #_version}"
     * @return the version.
     */
    public static String getVersion() 
    { 
        return _version; 
    }

    /**
     * Get the commit id: "{@value #_commit}"
     * @return the commit id.
     */
    public static String getCommit() 
    { 
        return _commit; 
    }

    /**
     * Get the branch: "{@value #_branch}"
     * @return the branch.
     */
    public static String getBranch() 
    { 
        return _branch; 
    }

    /**
     * Get the project status: "{@value #_status}"
     * @return the status.
     */
    public static String getStatus() 
    { 
        return _status; 
    }

    /**
     * Get the major version number.
     * @return the major version number
     * @throws NumberFormatException if version is in the wrong format.
     * @throws IndexOutOfBoundsException if version is in the wrong format.
     */
    public static int getMajorVersion() 
    { 
        return Integer.parseInt(getVersion().substring(0, getVersion().indexOf('.'))); 
    }
    
}

